"""True AI image-to-video via LTX-2.3, headless, with an OS-aware backend.

On Apple Silicon the clip is generated by the ltx-2-mlx CLI; everywhere else by
diffusers + PyTorch (``ltx_torch.py``, CUDA when available). Both produce the
same short raw clip; everything downstream here is portable ffmpeg.

AI video models produce short clips (~2-5s). Scene segments are much longer
(matched to narration), so we generate a real AI clip, then prefer LTX extension
for any remaining duration before falling back to a seamless boomerang loop.
(LTX extension is an mlx-CLI feature; the torch backend goes straight to the
loop fallback.)
"""

import subprocess
import tempfile
from pathlib import Path

from rich.console import Console

console = Console()


def _round_to(n: int, mult: int) -> int:
    return max(mult, (n // mult) * mult)


def _set_cache(models_dir: str) -> None:
    """Point the HF hub cache at an external drive. MUST run before importing
    diffusers/huggingface_hub, which read this env var at import time."""
    if models_dir:
        import os
        os.environ["HF_HUB_CACHE"] = str(Path(models_dir).expanduser())


def _ltx_mlx_dir() -> Path:
    """Checkout of ltx-2-mlx used by the MLX backend (config PTV_LTX_MLX_DIR)."""
    from ..config import PipelineConfig

    return Path(PipelineConfig().ltx_mlx_dir)


def _resolve_ltx_backend() -> str:
    """"mlx" or "torch", honoring config PTV_LTX_BACKEND (default auto)."""
    from ..config import PipelineConfig
    from ..utils.hw import resolve_backend

    return resolve_backend(PipelineConfig().ltx_backend)


def _finalize_trim(clip: Path, output_path: Path, duration_seconds: float,
                   resolution: tuple[int, int], fps: int) -> dict:
    """Scale/crop a clip to the target res and trim to the exact duration.
    Used when the AI clip is already long enough — preserves continuous motion
    (no boomerang), which looks far less static."""
    w, h = resolution
    vf = (
        f"scale={w}:{h}:force_original_aspect_ratio=increase,"
        f"crop={w}:{h},fps={fps},trim=duration={duration_seconds:.3f},setpts=PTS-STARTPTS"
    )
    proc = subprocess.run(
        ["ffmpeg", "-y", "-i", str(clip), "-vf", vf, "-r", str(fps),
         "-c:v", "libx264", "-preset", "fast", "-crf", "18",
         "-pix_fmt", "yuv420p", "-an", str(output_path)],
        capture_output=True, text=True, timeout=300,
    )
    if proc.returncode != 0 or not output_path.exists():
        return {"success": False, "error_message": f"finalize failed: {proc.stderr[-400:]}"}
    return {"success": True}


def _extend_to_duration(clip: Path, output_path: Path, duration_seconds: float,
                        resolution: tuple[int, int], fps: int) -> dict:
    """Make a seamless boomerang from a short clip, then loop it to the exact
    target duration and upscale. Two passes: boomerang, then -stream_loop."""
    w, h = resolution
    with tempfile.TemporaryDirectory() as td:
        boom = Path(td) / "boom.mp4"
        # Pass 1: scale/crop to target, build forward+reversed boomerang.
        vf = (
            f"scale={w}:{h}:force_original_aspect_ratio=increase,"
            f"crop={w}:{h},setpts=PTS-STARTPTS,fps={fps}"
        )
        fc = (
            f"[0:v]{vf},split[a][b];"
            f"[b]reverse[r];"
            f"[a][r]concat=n=2:v=1[out]"
        )
        p1 = subprocess.run(
            ["ffmpeg", "-y", "-i", str(clip), "-filter_complex", fc, "-map", "[out]",
             "-r", str(fps), "-c:v", "libx264", "-preset", "fast", "-crf", "18",
             "-pix_fmt", "yuv420p", "-an", str(boom)],
            capture_output=True, text=True, timeout=300,
        )
        if p1.returncode != 0 or not boom.exists():
            return {"success": False, "error_message": f"boomerang failed: {p1.stderr[-400:]}"}

        # Pass 2: loop the boomerang to the exact duration.
        p2 = subprocess.run(
            ["ffmpeg", "-y", "-stream_loop", "-1", "-i", str(boom),
             "-t", f"{duration_seconds:.3f}", "-r", str(fps),
             "-c:v", "libx264", "-preset", "fast", "-crf", "18",
             "-pix_fmt", "yuv420p", "-an", str(output_path)],
            capture_output=True, text=True, timeout=300,
        )
        if p2.returncode != 0 or not output_path.exists():
            return {"success": False, "error_message": f"loop failed: {p2.stderr[-400:]}"}
    return {"success": True}


def _probe_duration(path: Path) -> float | None:
    proc = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True,
        text=True,
        timeout=20,
    )
    if proc.returncode != 0:
        return None
    try:
        return float(proc.stdout.strip())
    except ValueError:
        return None


def _ltx_extend_clip(
    clip: Path,
    output_path: Path,
    prompt: str,
    extend_seconds: float,
    models_dir: str,
) -> dict:
    """Extend an existing LTX clip using ltx-2-mlx's extend command."""
    extend_frames = max(1, int(extend_seconds * 3))  # 24fps / 8 latent compression.
    cmd = [
        "uv",
        "run",
        "ltx-2-mlx",
        "extend",
        "--prompt",
        prompt,
        "--output",
        str(output_path),
        "--video",
        str(clip),
        "--extend-frames",
        str(extend_frames),
        "--direction",
        "after",
    ]
    env = dict(__import__("os").environ)
    if models_dir:
        env["HF_HUB_CACHE"] = str(Path(models_dir).expanduser())
    proc = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=3600,
        cwd=str(_ltx_mlx_dir()),
        env=env,
    )
    if proc.returncode != 0 or not output_path.exists():
        tail = (proc.stderr or proc.stdout or "")[-500:]
        return {"success": False, "error_message": f"ltx extend exited {proc.returncode}: {tail}"}
    return {"success": True}


def generate_ltx_clip(
    image_path: Path,
    output_path: Path,
    duration_seconds: float,
    prompt: str = "",
    resolution: tuple[int, int] = (1920, 1080),
    fps: int = 30,
    model_id: str = "Lightricks/LTX-Video",
    steps: int = 25,
    gen_width: int = 768,
    gen_height: int = 512,
    clip_seconds: float = 4.0,
    models_dir: str = "",
    prefer_extend: bool = True,
    max_frames: int = 97,
    anchor_last_frame: bool = True,
    cfg_scale: float = 3.0,
    stg_scale: float = 1.0,
) -> dict:
    """Generate a real AI image-to-video clip, extended to duration_seconds.

    Returns {success, video_path, duration, error_message}.
    """
    image_path = Path(image_path)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    _set_cache(models_dir)

    try:
        gen_fps = 24
        max_model_frames = _round_to(max(int(max_frames) - 1, 8), 8) + 1
        want = max(int(duration_seconds * gen_fps), int(clip_seconds * gen_fps))
        num_frames = min(_round_to(want, 8) + 1, max_model_frames)
        covers = (num_frames / gen_fps) >= duration_seconds - 0.05

        gw = _round_to(gen_width, 32)
        gh = _round_to(gen_height, 32)

        motion_prompt = prompt.strip() or (
            "Animate the reference image with natural subject motion while preserving "
            "identity, style, and composition."
        )
        anchor_count = 1
        if anchor_last_frame and num_frames > 1:
            anchor_count += 1
        backend = _resolve_ltx_backend()
        console.print(
            f"[blue]LTX i2v ({backend}): {image_path.stem} {gw}x{gh} {num_frames}f "
            f"({anchor_count} image anchors, {'direct' if covers else 'loop/extend'})[/blue]"
        )

        with tempfile.TemporaryDirectory() as td:
            short = Path(td) / "ltx_short.mp4"

            if backend == "mlx":
                image_args = ["--image", str(image_path), "0", "1.0"]
                if anchor_last_frame and num_frames > 1:
                    image_args.extend(["--image", str(image_path), str(num_frames - 1), "0.85"])

                # Use ltx-2-mlx CLI for native Apple Silicon inference
                cmd = [
                    "uv", "run", "ltx-2-mlx", "generate",
                    "--prompt", motion_prompt,
                    "--output", str(short),
                    *image_args,
                    "--width", str(min(gw, 704)),
                    "--height", str(min(gh, 480)),
                    "--frames", str(num_frames),
                    "--frame-rate", str(gen_fps),
                    "--steps", str(steps),
                    "--cfg-scale", str(cfg_scale),
                    "--stg-scale", str(stg_scale),
                    "--two-stage",
                ]

                env = dict(__import__("os").environ)
                if models_dir:
                    env["HF_HUB_CACHE"] = str(Path(models_dir).expanduser())

                console.print("[blue]  Running ltx-2-mlx generate…[/blue]")
                proc = subprocess.run(
                    cmd, capture_output=True, text=True, timeout=3600,
                    cwd=str(_ltx_mlx_dir()), env=env,
                )

                if proc.returncode != 0 or not short.exists():
                    tail = (proc.stderr or proc.stdout or "")[-500:]
                    return {"success": False, "video_path": str(output_path),
                            "duration": None, "error_message": f"ltx-2-mlx exited {proc.returncode}: {tail}"}
            else:
                from .ltx_torch import generate_short_clip

                gen = generate_short_clip(
                    image_path=image_path, output_path=short, prompt=motion_prompt,
                    width=min(gw, 704), height=min(gh, 480),
                    num_frames=num_frames, frame_rate=gen_fps, steps=steps,
                    cfg_scale=cfg_scale, stg_scale=stg_scale,
                    model_id=model_id, models_dir=models_dir,
                )
                if not gen["success"] or not short.exists():
                    return {"success": False, "video_path": str(output_path),
                            "duration": None, "error_message": gen["error_message"]}

            # LTX extension is an mlx-CLI feature; the torch backend loops instead.
            if covers:
                ext = _finalize_trim(short, output_path, duration_seconds, resolution, fps)
            elif prefer_extend and backend == "mlx":
                extended = Path(td) / "ltx_extended.mp4"
                short_duration = _probe_duration(short) or (num_frames / gen_fps)
                extend_seconds = max(duration_seconds - short_duration, 0.5)
                console.print(f"[blue]  Extending LTX motion by {extend_seconds:.1f}s…[/blue]")
                ext = _ltx_extend_clip(short, extended, motion_prompt, extend_seconds, models_dir)
                if ext["success"]:
                    ext = _finalize_trim(extended, output_path, duration_seconds, resolution, fps)
                else:
                    console.print(
                        f"[yellow]  LTX extend failed ({ext['error_message']}); loop fallback[/yellow]"
                    )
                    ext = _extend_to_duration(short, output_path, duration_seconds, resolution, fps)
            else:
                ext = _extend_to_duration(short, output_path, duration_seconds, resolution, fps)
            if not ext["success"]:
                return {"success": False, "video_path": str(output_path),
                        "duration": None, "error_message": ext["error_message"]}

        from .kenburns import _ffprobe_duration
        actual = _ffprobe_duration(output_path)
        console.print(f"[green]  -> {output_path} ({actual:.2f}s, real AI motion)[/green]")
        return {"success": True, "video_path": str(output_path), "duration": actual,
                "error_message": None}

    except subprocess.TimeoutExpired:
        return {"success": False, "video_path": str(output_path), "duration": None,
                "error_message": "ltx-2-mlx timed out after 3600s"}
    except Exception as e:  # noqa: BLE001
        return {"success": False, "video_path": str(output_path), "duration": None,
                "error_message": f"{type(e).__name__}: {e}"}
